Clair: handle messages from Clair v4
release-engineering/fedmsg_meta_umb pull request #92
Opened 2020-09-29 12:19 UTC by Allda

In Clair v4 a message format changed a bit. NVRA is no longer available
and it was replaced by image_id.

This commit also unifies strings in Clair related files. All strings
uses double quotes now.

2020-09-30 21:32 UTC, mikebonnet requested changes
The new message format which contains a `nvra` (NVR + arch) could be better supported.

2020-09-30 21:32 UTC, mikebonnet commented on fedmsg_meta_umb/clair.py
> +            elif inner_msg.get("image_id"):
In what cases is `nvra` present? Why not check and display that, before defaulting to the `image_id`?

2020-09-30 21:32 UTC, mikebonnet commented on fedmsg_meta_umb/clair.py
> +            return set([inner_msg["nvr"].rsplit("-", 2)[0]])
You could parse a package name out of `nvra` in the same way.

2020-10-09 13:07 UTC, Allda commented
NVRA is only available in Clair v4 which was deployed only to dev environment. Stage and prod are going to be released in the next weeks. Should I wait for all environment and then remove Clair v3 related code and replace it with the only v4? The current PR supports both versions.

2020-10-09 13:57 UTC, mikebonnet commented
> NVRA is only available in Clair v4 which was deployed only to dev environment. Stage and prod are going to be released in the next weeks. Should I wait for all environment and then remove Clair v3 related code and replace it with the only v4? The current PR supports both versions.

Supporting both formats is good (messages in the old format will still be available in the database), and I don't think there's any need to wait for deployments. My comments just meant that anywhere you're using `{nvr}.{arch}` with v3 messages, you could be using `{nvra}` with v4 messages, which would be more informative then displaying an `image_id`.

2020-11-18 21:37 UTC, mikebonnet commented
Could you rebase this?

2020-11-20 15:41 UTC, Allda commented
@mikebonnet sorry that it took me so long but I kind of forget about this PR. I added changes based on your comments, added a new message type, and rebased the PR.
Travis so very slow today so hopefully checks will pass soon.

2020-11-20 16:42 UTC, mikebonnet commented
This looks great, thanks!

2020-11-20 16:42 UTC, merged